### ISSUE TITLE
자바스크립트에서도 나쁜 주석?

### ISSUE THREAD

**Issue by heewhy** [brad-go/clean-code-study#20]
### 챕터

4. 주석

### 관련 내용

위치를 표시하는 주석

### 질문 사항

css작업이나 html 쪽에서는 주석으로 구역을 표시해서 오히려 가독성이 높아지는 경우가 있던 것 같습니다.
1. 자바 스크립트에서는 어떤가요?
2. 경우에 따라서는 좋은 주석이 될 수 있지 않을까요?

### 의견

1.  자바스크립트에서는 필요하다고 생각합니다. 각각의 함수가 어떤 식으로 연결이 되었는지를 확인이 필요하다고 생각해요.
2.  언어에 따라서는 좋은 주석일 수 있다고 생각합니다.

**Comment by brad-go** [comment]
저도 sass 같은 css 전처리기나 프레임워크를 사용하지 않고, css3만을 사용한다면 코드가 굉장히 길어지고 어느 부분을 나타내는지 알기 쉽지 않기 때문에 주석 처리를 통해 어느 요소를 나타내는지 구분해주는 것은 좋다고 생각합니다. 
자바스크립트의 경우 주석은 거의 필요하지 않습니다. 클린 코드 책의 내용과 같이 좋은 함수나 변수명으로 대체할 수 있다고 생각합니다.
